config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  resources :schedules, only: [:index, :show] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord

  has_many :schedulings
  has_many :schedules, through: :schedulings
end

app/models/schedule.rb
include SchedulesHelper

class Schedule < ApplicationRecord
  
  has_many :schedulings
  has_many :plants, through: :schedulings

  def self.today
    self.find_by(date: Date.today.to_s)
  end

  def self.collect_months
    self.find_each.collect { |r| to_date(r.date).month }.uniq
  end

  def self.records_in_month select_month
    self.find_each.select { |r| to_date(r.date).month == select_month  }
  end

  def self.create_monthly_records hash_shell
    self.collect_months.map { |month| hash_shell[month] = self.records_in_month(month) }
    hash_shell
  end

end

app/models/scheduler.rb
include SchedulesHelper

class Scheduler
  attr_reader :info, :start_date, :end_date, :dates

  #Start date requires format Year-Month-Day.
  #JSON file requires a keys "name" and "water_after" for the enclosed hash.
  def initialize json_file, start_date, number_of_weeks
    json = File.open("#{json_file}", "r").read
    @info = JSON::load(json)
    @start_date = to_date(start_date)
    @end_date = @start_date + (number_of_weeks * 7) 
  end
  
  def avoid_weekends date
    if date.saturday?
      date -= 1
    elsif date.sunday?
      date += 1
    end
    date
  end

  def create_schedule
    (@start_date..@end_date).each { |current_date| Schedule.create!(date: current_date.to_s) }
  end

  def create_plants
    @info.each { |plant_record| Plant.create!(name: plant_record["name"], watering_frequency_in_days: plant_record["water_after"].split[0].to_i) }
  end
          
  def create_scheduling
    create_schedule
    create_plants
    Plant.find_each.each do |plant_record|
      current_date = @start_date
      until current_date > @end_date
        watering_date = Schedule.find_by(date: current_date )
        watering_date.plants << plant_record
        current_date += plant_record[:watering_frequency_in_days]
        current_date = avoid_weekends(current_date)
      end
    end
  end

end

app/models/scheduling.rb
class Scheduling < ApplicationRecord
  belongs_to :schedule
  belongs_to :plant
end

app/models/watering_date.rb
class WateringDate < ApplicationRecord
  has_many :schedulings
  has_many :plants, through: :schedulings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
  def index
    @schedules = Schedule.includes(:plants)
    @todays_schedule = @schedules.today
    @plants_are_waterable = !@todays_schedule.plants.empty?
    @monthly_records = Hash.new
    @schedules.create_monthly_records(@monthly_records)
  end

  def show
    @schedule = Schedule.find(params[:id])
  end
end

app/controllers/watering_dates_controller.rb
class WateringDatesController < ApplicationController
  
  def index
    @watering_dates = WateringDate.all
  end

  def show
    @watering_date = WateringDate.find_by(date: Date.today.to_s)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def to_date date_string
    Date.strptime( date_string, "%Y-%m-%d")
  end

  def days_from_monday select_date
    date_num = to_date(select_date) .wday - 1
    date_num < 0 ? date_num = 6 : date_num
  end

  def print_date date_string
    real_date = to_date(date_string)
    "#{Date::MONTHNAMES[real_date.month]} #{real_date.day}, #{real_date.year}"
  end
end

app/helpers/watering_dates_helper.rb
module WateringDatesHelper
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tandem Plant Watering Schedule</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/index.html.erb
<h1>Tandem Watering Schedule</h1>

<div class="agenda">
  <h2>Today's Agenda</h2>
  <% if @todays_schedule && @plants_are_waterable %>
  <div class="datehead"><%= print_date(@todays_schedule.date) %></div>
  <div class = "plantshow"> 
    <% @todays_schedule.plants.each do |plant| %>
      <p><%= plant.name %></p>
    <% end %>
  </div>
  <% else %>
    <p>No watering scheduled for today! Check back tomorrow.</p>
  <% end %>
</div>

<div class="fullschedule">
  <h2>Full Schedule</h2>

  
    <% @monthly_records.each_pair do |month, dates| %>
      <div class="calendar">
      <div class="month">
        <%= Date::MONTHNAMES[month] %>
      </div>

      <ul class="weekdays">
        <li>Mo</li>
        <li>Tu</li>
        <li>We</li>
        <li>Th</li>
        <li>Fr</li>
        <li>Sa</li>
        <li>Su</li>
      </ul>

      <ul class="days">
        <% days_from_monday(@monthly_records[month].first.date).times do %>
          <li></li>
        <% end %>
        <% dates.each do |record| %>
          <% unless record.plants.blank? %>
            <li><%= link_to to_date(record.date).day.to_s, schedule_path(record) %></li>
          <% else %>
            <li><%= to_date(record.date).day.to_s %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/schedules/show.html.erb
<h1>Tandem Watering Schedule</h1>

<div class="datehead">
  <%=  print_date(@schedule.date)  %>
</div>
  <ul class="plantshow">
    <% @schedule.plants.each do |plant| %>
      <li><%= plant.name %></li>
    <% end %>
  </ul>
<div class="link">

<%= link_to "< Back to Home", root_path %>
</div>

app/views/watering_dates/index.html.erb
<h1>Tandem Watering Schedule</h1>

<div>
<h2>Today's Plants to Water</h2>
<% if @watering_dates.find_by(date: Date.today.to_s) && @watering_dates.find_by(date: Date.today.to_s).plants %>
  <strong><%= @watering_date.date %></strong> 
  <% @watering_date.plants.each do |plant| %>
    <p><em><%= plant %></em></p>
  <% end %>
<% else %>
  <p>No watering scheduled for today! Check back tomorrow.</p>
<% end %>
</div>

<div>
<h2>Full Schedule</h2>
<% @watering_dates.find_each do |watering_date| %>
  <% unless watering_date.plants.empty? %>
    <h3><%= watering_date.date %></h3>
    <% watering_date.plants.each do |plant| %>
      <p><%= plant.name %></p>
    <% end %>
  <% end %>
<% end %>
</div>